services:
    mosquitto:
        container_name: mosquitto
        hostname: mosquitto
        image: "eclipse-mosquitto:latest"  # Switched to official image
        restart: always
        tty: true
        environment:
            - USER_ID=1001
            - GROUP_ID=1001
        ports:
            - "1883:1883"
            - "9001:9001"
        networks:
            - dokploy-network
        volumes:
            - "/etc/localtime:/etc/localtime:ro"
            - "/etc/timezone:/etc/timezone:ro"
            - "../files/mosquitto-config:/opt/mosquitto/config"
            - "../files/mosquitto-data:/opt/mosquitto/data"
            - "../files/mosquitto-log:/opt/mosquitto/log"

networks:
    dokploy-network:
        driver: bridge
        external: true
