services:
    mosquitto:
        container_name: mosquitto
        hostname: mosquitto
        image: "4nxio/mosquitto:latest"
        restart: always
        tty: true
        environment:
            - USER_ID=1001
            - GROUP_ID=1001
        ports:
            - "1883:1883"
            - "9001:9001"
        networks:
            - dokploy-network
        volumes:
            - "/etc/localtime:../files/etc/localtime:ro"
            - "/etc/timezone:../files/etc/timezone:ro"
            - "mosquitto-config:../files/opt/mosquitto/config"
            - "mosquitto-data:../files/opt/mosquitto/data"
            - "mosquitto-log:../files/opt/mosquitto/log"

volumes:
    mosquitto-config:
        external: true
    mosquitto-data:
        external: true
    mosquitto-log:
        external: true

networks:
    dokploy-network:
        driver: bridge
        external: true
